Added validation border on select input, consistent with the input implementation
milestone-sys/web-design-system pull request #229
Opened 2020-08-31 13:22 UTC by fcchiaro83

Added validation border on select input, consistent with the input implementation

2020-08-31 13:42 UTC, mattsskea approved these changes

2020-08-31 13:42 UTC, mattsskea requested changes

2020-08-31 13:42 UTC, mattsskea commented on components/_form-select-input/select-input.scss
> +    @include msds-font('body-3');
use extend instead of include

2020-09-01 08:03 UTC, frfmilestone approved these changes

2020-09-01 11:10 UTC, frfmilestone submitted a review, later dismissed

2020-09-02 06:48 UTC, mattsskea approved these changes

2020-09-02 08:05 UTC, merged