Bug 320859 buttons
milestone-sys/web-design-system pull request #237
Opened 2020-09-21 10:57 UTC by ms-Danny

had to do some research to make it work in main solution and i had to add icon left modifier class for the ButtonIconAlignmentSelectionFactory selection factory. i also removed the icon modifer as it was redundant and no longer used in scss

2020-09-21 11:37 UTC, fcchiaro83 requested changes

2020-09-21 11:37 UTC, fcchiaro83 commented on components/_buttons/button/buttons.scss
> +    //display: inline-block;
remove commented out code, if not used :)

2020-09-21 11:37 UTC, fcchiaro83 commented on components/_buttons/button/buttons.scss
> +      //display: inline-block;
remove commented out code, if not used :)

2020-09-21 11:37 UTC, fcchiaro83 commented on components/_buttons/button/buttons.scss
> +  &.disabled,
Add disabled class on the svg icon as well

2020-09-21 12:05 UTC, fcchiaro83 approved these changes

2020-09-22 09:56 UTC, frfmilestone approved these changes

2020-10-06 09:27 UTC, fcchiaro83 approved these changes

2020-10-06 09:27 UTC, merged