Feature/360514 add flat icons
milestone-sys/web-design-system pull request #246
Opened 2020-10-08 13:20 UTC by ms-Danny

2020-10-08 13:29 UTC, SteRed submitted a review, later dismissed

2020-10-08 15:20 UTC, mattsskea requested changes
You did a really good job, its hard to figure out which direction to go with a lot of this when we have designers with 1 opinion, senior devs with another, other devs (Me) with other opinions and then the implementation and cascading effects from changes and how they impact MSDS and prod.

I have given you as much feedback as I could, after looking over everything. I have tried be be thorough but- I could of missed something so I think Pawel and or Francesco should take a glimpse also. I will do one more check on Monday but I feel your pain <3
Too many requested changes with miscoordination and too little time :(

But my overall comment would relate to the updated svg values, I know Stephan wants the values to match the names and I know Martin wants the names to match the names they use in the design team.
I would suggest finding out if our team and the content editors have the time to update any old svg implementations to use the new values, that means we need to update code and CE need to update selected icons from selection factories. If we can get the time to do this in our current and next sprint then we can ignore my comments regarding values.
If we can't get the time to do that, we need to fix the values and svg names in the PR

2020-10-09 07:57 UTC, ms-Danny commented on components/icons/icons.list.js
> -  { name: 'IP Cameras', value: '/Static/dist/msds-spritemap.svg#ip-cameras', previewValue: '#ip-cameras' },
All the icons are there in the branch and referenced in the file try look at the file and not just changes, you should find them there as well

2020-10-09 07:58 UTC, ms-Danny commented on components/icons/icons.list.js
> -    value: '/Static/dist/msds-spritemap.svg#list-horisontal',
Both the files and the references are still in the branch

2020-10-09 08:01 UTC, ms-Danny commented on components/icons/icons.list.js
> +    value: '/Static/dist/msds-spritemap.svg#social-linkedin',
i dont see used anywhere in main solution. searched for msds-spritemap.svg#linkedin

i only found this one <use xlink:href="/Static/Img/Icons/icons.svg#linkedin"></use>

2020-10-09 08:03 UTC, ms-Danny commented on components/icons/icons.list.js
> +    value: '/Static/dist/msds-spritemap.svg#transaction',
the only reference i found in main for this is Source\Workspaces\WEB\Main\Web_dev\Milestone.Web.Main\Milestone.Web.Main.Site\Static\dist\icons.list.js

and that will be automatically updated with NPM i asked pawel as well

2020-10-12 07:38 UTC, mattsskea submitted a review, later dismissed

2020-10-12 12:15 UTC, fcchiaro83 approved these changes

2020-10-12 12:41 UTC, merged